# 텐서의 개념
텐서(tensor) : 다차원 넘파이 배열에 데이터
<br>
랭크: n차원 데이터의 축의 개수.
<br>
예를 들어 3D 텐서에는 3개의 축이 있고, 행렬은 2개의 축. numpy 라이브러리에서는 ndim 속성에 저장.

## 텐서의 종류

**벡터데이터**
- 랭크2의 텐서 (n,k) -> (samples,features)
    각 샘플이 피처로 구성<br>
    
**시계열 또는 시퀀스 데이터**
- 랭크3의 텐서 (n,k,i) -> (samples,timestep,features)
    각 샘플이 i의 길이를 가지는 피처로 구성<br>

**이미지 데이터**
- 랭크4의 텐서 (n,k,i,j) -> (samples,height,width,channels)
    각 샘플이 2차원 픽셀로 이루어지고 픽셀이 수치(채널)값을 가짐
    <br>
    (흑백은 채널이 1, 컬러는 3)

**동영상 데이터**
- 랭크5의 텐서 (n,k,i,j,x) -> (samples,frame,height,width,channels)
    각 샘플이 길이가 k(frame)인 이미지 데이터 


### 텐서연산

ex) relu함수의 연산

output=relu(dot(W,input)+b)

relu(x) = > max(x,0)으로 계산(relu함수는 0보다 크면 x를 반환하고 0보다 작으면 0을 반환하는 함수를 가지고있기 때문)

In [13]:
#Lelu함수를 함수로 생성
def relu(x):
    assert len(x.shape)==2
    x=x.copy() # 원본유지
    for i in range(x.shape[0]): # 랭크2인 텐서 x의 행
        for j in range(x.shape[1]): # 랭크2인 텐서 x의 열
            x[i,j]=max(x[i,j],0) # 0보다 크면 x를 반환하고 0보다 작으면 0을 반환
    return x

In [19]:
# 2랭크 텐서의 덧셈 함수
def tensor_add(x,y):
    assert len(x.shape)==2
    assert x.shape==y.shape
    x=x.copy() # 원본유지
    for i in range(x.shape[0]): # 랭크2인 텐서 x의 행
        for j in range(x.shape[1]): # 랭크2인 텐서 x의 열
            x[i,j]+=y[i,j] # 덧셈
    return x

### 텐서 덧셈 연산

In [5]:
import numpy as np

In [7]:
import time

In [8]:
x=np.random.random((20,100))
y=np.random.random((20,100))

In [6]:
z=x+y

NameError: name 'x' is not defined

In [10]:
# 넘파이의 덧셈 연산 속도
t=time.time()
for i in range(1000):
    z=x+y
    z=np.maximum(z,0)
print("시간 : {0:.2f} 초".format(time.time()-t))

시간 : 0.02 초


In [22]:
# 텐서플로우 덧셈 연산 속도
t=time.time()
for i in range(1000):
    z=tensor_add(x,y)
    z=relu(z)
print("시간 : {0:.2f} 초".format(time.time()-t))

시간 : 1.82 초


### 크기가 다른 두 텐서의 연산
크기가 다른 두 텐서의 연산은 작은텐서가 큰텐서에 맞추어져 연산이 이루어져 **브로드캐스팅**됨
1. 큰 텐서의 차원에 맞게 작은 텐서에 축이 추가됨
2. 작은 텐서가 새 축을 따라 큰 텐서의 크기에 맞게 반복됨

In [34]:
x=np.random.random((64,3,32,10))
y=np.random.random((32,10))

In [36]:
z=x+y

x와 y의 차원이 다른데도 덧셈 연산이 실행됨

In [39]:
# 결과는 x의 ndim에 맞게 출력
z.shape

(64, 3, 32, 10)

### 텐서 곱셈 연산

In [24]:
# 넘파이의 곱셈 연산
x=np.random.random((32,))
y=np.random.random((32,))
# z=x*y
z=np.dot(x,y)
z

7.3774892821381535

In [30]:
# 2랭크 텐서의 곱셈 함수
def tensor_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape==y.shape
    z=0 # 원본유지
    for i in range(x.shape[0]):
        z+=x[i]*y[i] # 덧셈
    return z

In [31]:
tensor_dot(x,y)

7.377489282138153

## 텐서의 크기변환

#### 텐서의 형태 변환

In [47]:
x=np.array([[1,2],
          [3,4],
          [5,6]])

In [48]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
x.shape

(3, 2)

In [50]:
x=x.reshape((6,1))

In [51]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [52]:
x.shape

(6, 1)

#### 텐서의 전치

In [54]:
x=np.zeros((300,20))
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [55]:
x.shape

(300, 20)

In [56]:
x=np.transpose(x)

In [57]:
x.shape # 데이터프레임에서 .T와 같은 함수

(20, 300)